### ISSUE TITLE
Fish pepper blocks get not upated sometimes

### ISSUE THREAD

**Issue by jamesnetherton** [fabric8io-images/s2i#101]
We make use of some fish-pepper blocks for Jolokia and Jmxexporter. If I modify any of the block config params, the changes never see seem to show up in the fish-pepper generated Dockerfile(s).

**Comment by jamesnetherton** [comment]
Doh! User error, was running fish-pepper within the templates directory instead of the parent karaf or java directory.

**Comment by rhuss** [comment]
Yeah, I sometimes also see some stale block, not update by git. I have to investigate this further but the quickest workaround is to remove the .fp-git-blocks directory completely.

**Comment by jamesnetherton** [comment]
There also seems to be issues on the maintenance branches.

For instance, if I run fish-pepper on the v2.0.0-redhat branch, I get:

```
* Loading external blocks
  Cloning https://github.com/fabric8io/run-java-sh.git (Branch: v1.0.0-redhat)
  Cloning https://github.com/fabric8io/agent-bond.git (Branch: v1.0.0-redhat)
```
But when I look in the `.fp-git-blocks` sub directories, the branches checked out are not as expected:

```
git rev-parse --abbrev-ref HEAD
master
```
