### ISSUE TITLE
additional EXPOSE port-number (and customizable via EXPOSE_PORT environment variable)

### ISSUE THREAD

**Issue by vorburger** [fabric8io-images/s2i#115]
Unless I'm [missing something in how this is to be used](https://github.com/fabric8io-images/s2i/issues/112), don't we need to have a way to specify which port, in addition to 8778 and 9779, is to be EXPOSE'd in the Dockerfile for the _"microservices with a flat classpath"_ (quote from README) to be accessible by a Service and Route?

Because without hacking that, I cannot get e.g. this to work:

    oc new-app fabric8/s2i-java~https://github.com/vorburger/s2i-java-example
    oc expose svc/s2i-java-example --port=8080
    oc status -v
    ...
    Warnings:
      * route/s2i-java-example has a port specified (8080) but svc/s2i-java-example has no such targetPort.

PS: An `oc expose svc/s2i-java-example` will create a route on port 8778, which of course isn't what one would want.

**Comment by vorburger** [comment]
@rhuss / all: if PR #117 is not the right solution for this problem, then how does one do the above right if not direct Docker but with OpenShift `oc new-app` - how is an example like this (above) supposed to work without an EXPOSE?

**Comment by rhuss** [comment]
@vorburger what's about 

```
oc expose svc/s2i-java-example --port=8080 --target-port=8080
```

?

Actually I'm not sure how to reliably define a default port to expose in the s2i builder image as this is supposed to run all sort of Maven builds and obviously the builder image can not know the port of the application which is build with this image in advance.

I wonder, whether the S2I mechanism itself has an answer for this as I suppose to be an issue for any s2i source build. I think there should be a s2i config which defines this port and which uses the s2i build mechanism to expose on the final image it creates after a build.

Let me research a bit ...

**Comment by gunnarmorling** [comment]
Hey @rhuss, any further insights on that one? What you suggest above doesn't seem to work for me, as the image doesn't export port 8080. So I'm wondering how I'd e.g. use this image to run WildFly Swarm on OpenShift. Glad about any ideas you may have :)

**Comment by rhuss** [comment]
Actually in a Dockerfile `EXPOSE` is always a _recommendation_. You always can export any port from the container without declaring it first in the Dockerfile/Image.

Historically the only reason why `EXPOSE` was introduced in Dockerfiles is, that a `docker run -P` can file all ports exposed. Still, you can use `docker run -p <any local port>:<any container port>` without previously declaring.

And sorry, haven't done my homework yet. Not sure whether there is an S2I mean to provide this meta data for the resulting image.

**Comment by gunnarmorling** [comment]
Hey @rhuss, any news on this one? I currently need to patch each application using that S2I builder:

    oc patch service my-app -p '{ "spec" : { "ports" : [{ "name" : "8080-tcp", "port" : 8080, "protocol" : "TCP", "targetPort" : 8080 }] } } }'

It'd be really cool if this could be simplified a bit.

**Comment by rhuss** [comment]
@gunnarmorling sorry, no yet. It looks like that the `--target-port` options is only available for a [service generator](https://github.com/openshift/openshift-docs/pull/3577/files), but since the service has been already generated by `oc new-app`, this doesn't help.

Instead, we need to convince `oc new-app` that when it creates a service additional ports need to be taken into account. This needs to be somehow specified as the generic s2i image has no insight into the app and which ports are exposed by the build app. Propbably this can be don by some env vars which allows the `assemble` script to give the service generation mechanism of `oc new-app` some hints for the service to export. Still I have to find out how it really works. Also wonder, how the productised Java S2I image from CE allows to expose application specific ports. 

@goldmann any idea how a custom port can be exposed by an s2i builder image so that it's picked up for the service generated via `oc new-app` ?

**Comment by edewit** [comment]
@vorburger I think it's a good idea it's a sensible default

**Comment by vorburger** [comment]
Merged. FTR: I've not really tested if, how and where one can customize that new `EXPOSE_PORT`.

**Comment by vorburger** [comment]
FTR: It's not actually customizable; for now, `EXPOSE_PORT` got removed again due to #206.

**Comment by vorburger** [comment]
> FTR: It's not actually customizable; for now, EXPOSE_PORT got removed again due to #206.

strike that, [I reverted that](https://github.com/fabric8io-images/s2i/commit/c23d43fcbf0b53dc53a4fec87abed75f73337761), so `EXPOSE_PORT` is back; see full story in #206.

**Comment by brian316** [comment]
How is this still an issue in 2022. What if the application defaults to a different port like for mysql server? or javascript frameworks? I have to manually update the services target port for it to work but it doesnt let you in the command line...
