### ISSUE TITLE
AB_JOLOKIA_PORT customization probably isn't working, because it's hard-coded in the Dockerfile

### ISSUE THREAD

**Issue by vorburger** [fabric8io-images/s2i#116]
The [README](https://github.com/fabric8io-images/s2i/tree/master/java/images/jboss) says:

> AB_JOLOKIA_PORT : Port to use (Default: 8778)

but I doubt customizing this actually works - because while [it's dynamic here](https://github.com/fabric8io-images/s2i/blob/master/java/images/jboss/jolokia-opts#L16), [it's then hard-coded in the Dockerfile](https://github.com/fabric8io-images/s2i/blob/master/java/images/jboss/Dockerfile#L65) ...

**Comment by rhuss** [comment]
Yes, the expose doesn't make much sense that way. but as said elsedwhere `EXPOSE` is only meta data, we can skip it and still open the port.

**Comment by rhuss** [comment]
So we probably should just remove the `EXPOSE` line in the Dockerfile.

**Comment by vorburger** [comment]
> as said elsedwhere EXPOSE is only meta data, we can skip it and still open the port.
> So we probably should just remove the EXPOSE line in the Dockerfile.

just FTR so that I can find this again, this is the discussion over in #115
