### ISSUE TITLE
add support for Gradle builds in addition to Maven

### ISSUE THREAD

**Issue by vorburger** [fabric8io-images/s2i#118]
Would there be any interest in a contribution to this project to build Gradle projects, in addition to Maven?

It doesn't seem that hard to [add a something like this here](https://github.com/fabric8io-images/s2i/blob/master/java/images/jboss/s2i/assemble):

    if [ -f "${S2I_SOURCE_DIR}/*.gradle*" ]; then

note the use of `*.gradle*` in order to also allow `build.gradle.kts` for the Gradle Kotlin DSL, and [myProjectName.gradle](https://docs.gradle.org/current/userguide/command_line_interface.html#_environment_options).

if present, then run something like `./gradlew --gradle-user-home=${S2I_ARTIFACTS_DIR}/gradle-home --project-cache-dir=${S2I_ARTIFACTS_DIR}/gradle-project-cache build` (TBC, probably with a GRADLE_ARGS and/or GRADLE_ARGS_APPEND, similar to the MAVEN_ARGS and MAVEN_ARGS_APPEND).

I would limit this to support only the Gradle wrapper, and not even bother to add a Gradle distribution into the image. Just because using the wrapper is VERY widespread in Gradle based project (contrary to [the maven-wrapper](https://github.com/takari/maven-wrapper)), and saves a ton of "which version" hassles, which for frequently releasing Gradle is even more important than with Maven (BTW surprised we're on ancient Maven 3.3.3 instead of latest 3.5.2 here...). The overhead of downloading a Gradle distribution IMHO is manageable with incremental builds by preserving the --gradle-user-home and --project-cache-dir accross builds; in the bigger picture of typically many many dependencies, the Gradle distribution itself is really just another such dependency. 

BTW incremental builds with Gradle should be blazingly fast, not only avoiding dependency re-downloads, but truly incrementallying building code changes themselves (which never really works reliably in Maven; BTW I'm surprised [we don't do clean package instead of just package here](https://github.com/fabric8io-images/s2i/blob/master/java/images/jboss/s2i/assemble)).

It should also include the equivalent of https://github.com/fabric8io-images/s2i/issues/110.

**Comment by vorburger** [comment]
@rhuss @ctron @apupier @chirino @jamesnetherton how do you like https://github.com/fabric8io-images/s2i/pull/121 ? It works e.g. with https://github.com/vorburger/s2i-java-example/tree/gradle (if you want to try, note "git checkout gradle" branch...) - which something like https://github.com/fabric8io-images/s2i/issues/120 could "prove" on the PR (and ensure future non-regression for).

**Comment by toretest** [comment]
"/usr/local/s2i/assemble: line 214: ./gradlew: Permission denied" in minishift when try to build my own gradle project

**Comment by vorburger** [comment]
Hello, thanks for the interest. FYI I don't work on this project at all
anymore, so this is just a quick tip for you, I won't be able to follow up
further:

I'm assuming you are a Windows user, with a filesystem without permissions,
so locally gradlew in cmd.exe works.

From the error message, it looks like the "gradlew" script, which is in
YOUR project, the one you're trying to build, not this project here, is
just missing "chmod +x gradlew".. do that, from a Linux not Windows
environment (or WSL), commit it (FYI git preserves file permissions), and
it should work.

I'm happy to see that the work I did here a while ago is still useful to
people.

>
