### ISSUE TITLE
Executable fat WARs e.g. from Spring Boot should work without requiring setting JAVA_APP_JAR with fixed version

### ISSUE THREAD

**Issue by vorburger** [fabric8io-images/s2i#123]
[I'm finding that one currently has to put this](https://github.com/vorburger/alf.io/blob/dd0af73bb5be51fb27e24112841c7b0db16a39c9/.s2i/environment) e.g. into a `.s2i/environment`, e.g. to use this with Spring Boot:

    ARTIFACT_COPY_ARGS=*-boot.war
    JAVA_APP_JAR=alfio-1.14-SNAPSHOT-boot.war

when it would be much nicer (and avoid confusion on versin bumps) if we could support wildcard expansion in JAVA_APP_JAR, just like it is allowed in other environment variables:

    ARTIFACT_COPY_ARGS=*-boot.war
    JAVA_APP_JAR=*-boot.war

**Comment by rhuss** [comment]
Actually, `JAVA_APP_JAR` handling is inherited from [run-java.sh](https://github.com/fabric8io-images/run-java-sh) so we might should add this there. btw, you know that if you only have a single jar in the directory, it gets updated automatically ?

@vorburger would you mind to open an issue over there to track it ? It would be automatically picked up by this image (when the dep to run-java-sh block is updated) and also other images (like the plain java image) would benefit, too.

thanks !

**Comment by vorburger** [comment]
> btw, you know that if you only have a single jar in the directory, it gets updated automatically ?

yup, I noticed that playing with it... but FYI it's quite typical e.g. in Spring Boot projects that some build produces some JAR and/or WAR and then some Maven / Gradle plugin post-processes that to be executable and what not - and, typically, leaves the original in place.

> @vorburger would you mind to open an issue over there to track it ?

==> https://github.com/fabric8io-images/run-java-sh/issues/65 ok?

**Comment by rhuss** [comment]
perfect, thanks !

**Comment by vorburger** [comment]
https://github.com/fabric8io-images/run-java-sh/issues/79 is probably a better approach actually...

**Comment by vorburger** [comment]
> [fabric8io-images/run-java-sh#79](https://github.com/fabric8io-images/run-java-sh/issues/79) is probably a better approach actually...

so if/when @rhuss merges https://github.com/fabric8io-images/run-java-sh/pull/80, and makes a new release of run-java-sh, then we can fix this here "just" by bumping the version ... what would be neat is to have our `test.sh` cover this as well with a (TBD) `java/examples/springboot-gradle|maven` ...

**Comment by vorburger** [comment]
> would be neat is to have our `test.sh` cover this as well with a `java/examples/springboot-gradle|maven` ...

https://github.com/fabric8io-images/s2i/compare/master...vorburger:example-spring-gradle

**Comment by rhuss** [comment]
run-java PRs are merged and a v1.3.1 release released, so I think we are good with updating it here.

**Comment by vorburger** [comment]
> run-java PRs are merged and a v1.3.1 release released, so I think we are good with updating it here.

Nope, it's actually broken... :smiling_imp: see https://github.com/fabric8io-images/run-java-sh/pull/80
