### ISSUE TITLE
Support for incremental build

### ISSUE THREAD

**Issue by surajnarwade** [fabric8io-images/s2i#125]
`fabric8/s2i-java` should support incremental build so that build time will get reduced

**Comment by vorburger** [comment]
@surajnarwade yeah that would be nice - if it doesn't already work, or at least partially.. have you noticed that there is a [s2i/save-artifacts](https://github.com/fabric8io-images/s2i/blob/master/java/images/jboss/s2i/save-artifacts)? I'm not crystal clear yet how this all works. Maybe I'll look more into some time (after other things I recently raised here).  If you know more about it, contribute here! :smile:

**Comment by rhuss** [comment]
This image supports incremental builds. Or at least, it is supposed to ;-)

In an incremental build, it will reuse the ~/.m2/repository local cache. This helps in speeding up the build, but as this copying also takes quite some time it is not that performance boot as you might expect.

I'm closing this issue, but if you have problems with the incremental build, please open a new issue with a problem description.
