### ISSUE TITLE
Which base image to use for rhel

### ISSUE THREAD

**Issue by mmaier2** [fabric8io-images/s2i#13]
We have valid RHEL Subscriptions so I would like to build
 s2i/java/Dockerfile.rhel
But it can't find the references base image
$ docker pull jboss-base-7/jdk8:latest
Trying to pull repository registry.access.redhat.com/jboss-base-7/jdk8 ... not found
Trying to pull repository docker.io/jboss-base-7/jdk8 ... not found
Error: image jboss-base-7/jdk8:latest not found

**Comment by alberttwong** [comment]
You can pull official FIS images from registry.access.redhat.com

**Comment by enjoyjoy** [comment]
FROM jboss-base-7/jdk8:1.2-28

where is the base image?

is not found   on neither docker hub nor regirtry.access.redhat.com

**Comment by rhuss** [comment]
Actual it could be that the base image is not exposed via registry.access.redhat.com (sorry really no idea how the images are exposed externally), but you can download the full product image from https://access.redhat.com/containers/#/registry.access.redhat.com/jboss-fuse-6/fis-java-openshift

Note also, that the product image might differ from the Dockerfile presented here (as it is build from a different repository)
