### ISSUE TITLE
sandbox/ ?

### ISSUE THREAD

**Issue by vorburger** [fabric8io-images/s2i#134]
@apupier @rhuss is what is in sandbox/ in this repo still used & maintained, or should it be removed?

**Comment by vorburger** [comment]
@rhuss without any reply from @apupier I'm inclined to raise a PR to `rm -rf sandbox/` - OK for you?

@jamesnetherton @dhirajsb any objection?

**Comment by apupier** [comment]
sorry, I don't know this code repository. I have no idea what the sandbox/ folder is used for. I provided only a bugfix and typo fix.

**Comment by rhuss** [comment]
yes, we can remove it
