### ISSUE TITLE
Mismatch between archive type generated by docker-maven-plugin and one needed by deploy-and-run.sh

### ISSUE THREAD

**Issue by lburgazzoli** [fabric8io-images/s2i#15]
According to [karaf quickstart's pom](https://github.com/fabric8io/ipaas-quickstarts/blob/master/quickstart/karaf/camel-amq/pom.xml#L298) the archive type is zip whereas deploy-and-run.sh expects a zip, this cause the following error to appear when deploying with f8-local-deploy :

```
Missing or more than one assembly archive file *.tar.gz in /deployments
```

I'll try to submit a PR

**Comment by lburgazzoli** [comment]
Or as alternative set

```xml
    <archiveTarGz>false</archiveTarGz>
    <archiveTarGz>true</archiveTarGz>
```

for karaf-maven-plugin

**Comment by rhuss** [comment]
thanks for pointing this out, a PR is highly appreciated ;-)

**Comment by lburgazzoli** [comment]
this #16  is to handle zip archives in deploy-and-run.sh but I do not know what is the best solution, switching to tar.gz could be enough (would impact quickstarts).

Let me know.

**Comment by lburgazzoli** [comment]
@rhuss I've re-worked the PR so the script can now handle both zip and tar.gz (zip has a precedence) 

- if it found 1 zip, use it
- if it found 1 tar.gz use it
- if it found multiple zip but a single tar, it will use the tar (same vice-versa)

Otherwise, it exits
