### ISSUE TITLE
include "envsubst" in container?

### ISSUE THREAD

**Issue by vorburger** [fabric8io-images/s2i#155]
My understanding is that the preferred way to pass non constant "configuration knobs" to container images is via environment variables. In OpenShift we have a the _Environment_ UI tab for this.

The `envsubst` util would be very handy to replace values in configuration files by environment values during an S2I build if it could easily be used in `.s2i/bin/assemble` (or even `.s2i/bin/run`). 

Would we open to including `envsubst` in the image? Or even in `FROM jboss/base-jdk` ?

**Comment by rhuss** [comment]
@vorburger which kind of configuration files do you have in mind ? pom.xml probably not as it then wouldn't be usable outside (and there will be a clash for plain Maven properties, too)

settings.xml ? Blindly replacing any `${ENV}` reference makes probably not much sense as this is to dangerous. How would we specify which configuration file's content should be templated ?

**Comment by vorburger** [comment]
@rhuss no no, not at all for `pom.xml` or `settings.xml` build infra but for applications themselves... 

Say you have some Java app which reads some config file. Assume that app/lib isn't smart enough to pick up `-D...` or `System.getenv("...)` and you cannot change it. So one wants some value in that config file to be configurable during the S2I image build. 

I've done something like this e.g. in https://github.com/OASIS-learn-study/swissarmyknife-minecraft-server/commit/7fff4c9a30e9cefbc7126833f4285880c0b97d16 (just as an illustration, could be anything else of course) but that's crude and ugly - `envsubst` seems nice for that, and one could want to use it in a `.s2i/bin/assemble` - if it was available in the base container image.

**Comment by rhuss** [comment]
my question still is how to specify the files that should be mangled with `envsubst`. I'm even not sure how to specify a config file to be used when running the built s2i file. 

Could you please provide a sample for this generic s2i image how this should be used ?
