### ISSUE TITLE
build.gradle ignored during build process.

### ISSUE THREAD

**Issue by viv816** [fabric8io-images/s2i#161]
Hi,

I am using s2i build process to build an app in OpenShift from Git source having a gradle project.
Builder image is "registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift" 

My project directory structure is as shown below
![s2i-gradle](https://user-images.githubusercontent.com/10990387/40300387-b175d0e6-5d1b-11e8-867e-bc14a1078080.PNG)

However, when I start the build process, the _assemble script_ echoes **"S2I source build with plain binaries detected"** instead of echoing **"S2I source build for Gradle detected, due to presence of a *.gradle* in ${S2I_SOURCE_DIR}"**

Why is the _assesmble script_  not detecting **build.gradle** from root folder?

Need help.

Thanks,

**Comment by vorburger** [comment]
@viv816 I suspect that this is most likey _"just"_ due to a version/release problem... The "registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift" Builder image "downstream" most likely does not, yet, include my work to add Gradle support to this project which was only recently merged here in the "upstream".

**Comment by viv816** [comment]
Thank you for the response.

When is the 'Gradle' support expected in builder image downstream so I can test and use in my project?

**Comment by vorburger** [comment]
> When is the 'Gradle' support expected in builder image downstream so I can test and use in my project?

@viv816 unfortunately that's not something that we (me at least) can answer in this GitHub issue tracker. 

You have 2 choices AFAIK, depending on your situation, pick what works better for you:

1. if your company has a commercial Red Hat OpenShift support subscription, you can try formally opening a support case / bring to the attention of your account manager your interest in Gradle not just Maven support in the Java S2I base image, and point to this GitHub issue in such discussions. In theory, such a request should ultimately reach OpenShift Product Management, who would make a decision if and when to pick this up, document and test and officially support it.

2. if you are trying this out at home / locally with minishift / for a hobby project / on the free OpenShift Online etc. etc. (or are a corporate which is fine with having no support, I guess), then you can just locally build and use this image yourself, at your own risk of course - it may break, Gradle support may get removed etc. etc. That's quite easy, actually: `oc new-build https://github.com/fabric8io-images/s2i --context-dir=java/images/jboss`.

Does this help you to understand how the process works, and shall we close this issue?

**Comment by viv816** [comment]
Thank you very much for the explaination and advice. 

I am learning about OpenShift etc, and simultaneously trying out/exploring things so we can implement it in commercial projects in future.
