### ISSUE TITLE
Recently change default directory from `/opt/jboss` to '/' breaks backward compability and could cause issues to end-users

### ISSUE THREAD

**Issue by vorburger** [fabric8io-images/s2i#169]
@rhuss & Co. I just ran into an interesting problem over on my https://github.com/OASIS-learn-study/s2i-minecraft-server/issues/7 which I thought would be worthwhile to point out to you guys here:

Something (presumably https://github.com/fabric8io-images/s2i/pull/165) recently changed the default directory which scripts such as `.s2i/bin/assemble` start with from `/opt/jboss` (RW) to '/' (RO) - and this, technically, breaks backward compability, and could cause issues to end-users (like it has for me).

If you think we can forget about, I take no offense if you just close this issue again.

Or should we explicitly put a cd `/opt/jboss` (back) somewhere?

**Comment by rhuss** [comment]
No change in the directory change was intended. The reason for #165 was that the jboss/openjdk image, seems not to be supported anymore and contains a vulnerable jdk. So we had to switch the based jdk and went for plain centos were we install the jdk on our own.

Not sure what actually changes the directory, so have to inverstigate that and happy to revert it to the original behaviour.

**Comment by vorburger** [comment]
@rhuss I actually [just worked around it](https://github.com/OASIS-learn-study/s2i-minecraft-server/commit/4c2c125a8b8781549459ef973bcb00daf7cb13e8) ;-) but have now anyway re-tested by  reverting that work around (and `docker rmi fabric8/s2i-java`), and can confirm that it's now fixed. 

Glad we caught this (early), hopefully this will avoid headaches for others!

**Comment by rhuss** [comment]
yeah, and thanks a lot for the heads up ! Good find.
