### ISSUE TITLE
Docker builds fail attempting to download Maven 3.3.3

### ISSUE THREAD

**Issue by jamesnetherton** [fabric8io-images/s2i#18]
Seems that Maven 3.3.3 is no longer available here:

http://www.apache.org/dist/maven/maven-3/

It's available here though:

https://archive.apache.org/dist/maven/maven-3

Should we stick with 3.3.3 or upgrade to 3.3.9?

**Comment by rhuss** [comment]
thanks for the heads up.

The reason for this specific Maven version was, that it's the last one supported in RHEL. So I suggest to stick to 3.3.3 for the moment.

Would be awesome if you could do a PR, would apply it immediately.
