### ISSUE TITLE
unzip missing

### ISSUE THREAD

**Issue by edewit** [fabric8io-images/s2i#184]
Some tools need unzip and this command seems to be removed in later versions

**Comment by vorburger** [comment]
Uhu ... this broke our https://github.com/OASIS-learn-study/swissarmyknife-minecraft-server :smile_cat: 

It's also what was reported on #171. Let me finally fix this RIGHT NOW ....

```
$ yum whatprovides unzip
unzip-6.0-38.fc28.x86_64 : A utility for unpacking zip files
Repo        : @System
Matched from:
Provide    : unzip = 6.0-38.fc28

unzip-6.0-38.fc28.x86_64 : A utility for unpacking zip files
Repo        : fedora
Matched from:
Provide    : unzip = 6.0-38.fc28

```
