### ISSUE TITLE
images/fedora/openjdk/11 instead of fedora-java11 etc.

### ISSUE THREAD

**Issue by vorburger** [fabric8io-images/s2i#196]
@rhuss has pointed out that instead of the _"flat"_ `images/fedora-java11` structure which #189 introduces for #160, we could in the future use FishPepper's "combinatorial multi-level" support to build e.g. `images/fedora/openjdk/11/64bit/jdk` (at the most extreme, or a suitable shortened version of this - depending on how much variability we ever anticipate).

The (non-S2I!) https://github.com/fabric8io-images/java project does this in its [images.yml](https://github.com/fabric8io-images/java/blob/master/images.yml), note its 3 level params (`base`, `version`, `type`), the respective `config` and the related `ignore-for` [in line 56](https://github.com/fabric8io-images/java/blob/148541abeed089274aae0e3061207c8d06ed874e/images.yml#L56).

**Comment by rhuss** [comment]
Agreed, that it makes much sense for maintaining (and that's exactly the purpose of fish-pepper to allow multiple, independent dimensions. Here: os=centos, rhel; version=8,11 plus maybe extra variants.

The question is, whether we want to have different image names as in https://github.com/fabric8io-images/java or doing everything under s2i-java with different tags (for the upstream images at least). 

Wdyt ?

**Comment by vorburger** [comment]
> The question is, whether we want to have different image names as in https://github.com/fabric8io-images/java or doing everything under s2i-java with different tags (for the upstream images at least).

I was thinking about that in #203 and decided to use tags.  My main reason for going that way was "discoverability", know what I mean? The one (small) problem I found is that https://hub.docker.com/r/fabric8/s2i-java/ (from the README) is "wrong".

**Comment by rhuss** [comment]
wdym with "wrong" ?  You mean the README on Docker Hub ? This is a file that has been manually added, and need to be edited on Docker Hub directly (as we are not using automated builds, but pushes the images via circleci).

Do you have karma on Docker hub for editing it ?

**Comment by vorburger** [comment]
> wdym with "wrong" ? You mean the README on Docker Hub?

Just that https://hub.docker.com/r/fabric8/s2i-java/ says "with OpenJDK 8" which (now) is no longer entirely accurate.

> This is a file that has been manually added, and need to be edited on Docker Hub directly

Oh! I just assumed that was https://github.com/fabric8io-images/s2i/blob/master/java/images/centos/README.md

> Do you have karma on Docker hub for editing it ?

Don't think so, at least I don't see an Edit button. I'm https://hub.docker.com/u/vorburger/ over there, in case you want to somehow "invite" me, if that's possible.

But simplest is perhaps if you would like to just go ahead and edit it?
