### ISSUE TITLE
Reduce size of image by remove number of layers

### ISSUE THREAD

**Issue by vorburger** [fabric8io-images/s2i#209]
It may be possible to reduce the size of our images, [currently at about 160-ish MB](https://hub.docker.com/r/fabric8/s2i-java/tags) by having less than [the 38 layers we have today](https://microbadger.com/images/fabric8/s2i-java) ?

According to https://opensource.com/article/18/7/building-container-images, it would probably help to concatenate all `RUN` [which we have here](https://github.com/fabric8io-images/s2i/blob/master/java/templates/Dockerfile) and perhaps `COPY` and `ADD` into a single one?

According to `docker history s2i-java` all those layers, except for the `yum update && install` one are not all that big though, so only a real test would show much that really save.

This https://dustymabe.com/2014/07/07/creating-your-own-minimal-docker-image-in-fedora/ and this https://goldmann.pl/blog/2014/03/06/creating-a-minimal-wildfly-docker-image/ have some other ideas.

**Comment by rhuss** [comment]
Yes, you can use concatenation in the Dockerfile templates to some extent. However because of the way how we modularize with fish-pepper this is not possible in a perfect way. Currenty I don't see a big issue, but lets do what we can for now.
