### ISSUE TITLE
JAVA_DIAGNOSTICS for s2i java 11 image uses deprecated and removed JVM options

### ISSUE THREAD

**Issue by muff1nman** [fabric8io-images/s2i#213]
Options such as PrintGCDateStamps are no longer valid.

**Comment by rhuss** [comment]
@vorburger I guess we need to updatre run-java.sh for this, right ? I.e. we probably need a version detection in this startup script.

**Comment by vorburger** [comment]
> Options such as PrintGCDateStamps are no longer valid.

@muff1nman but that's just a warning, it "works" anyway - or doesn't it for you? Curious.

Would you (@muff1nman) be willing to contribute a PR to https://github.com/fabric8io-images/run-java-sh (perhaps inspired by https://github.com/fabric8io-images/run-java-sh/pull/73/files) which does the trick?

>  we probably need a version detection in this startup script

yeah I guess, but in run-java-sh? From a (quick) look, it would seem that https://github.com/fabric8io-images//pull/73/files already added a `if [ "${JAVA_MAJOR_VERSION:-0}" -ge "10" ];` in some places... perhaps someone could build on top of that? (I'm unlikely to get to that at least this week.)

**Comment by rhuss** [comment]
BTW, I just submitted #214 which updates run-java.sh to not calculated defaults when running on Java 11.

**Comment by rhuss** [comment]
Yeah, would be interesting which option combo to use for diagnostics for Java 11. Unfortunately, I'm overloaded, but if someone finds out a good combination and creates a PR for run-java.sh I can do a release and rebase quickly.

**Comment by muff1nman** [comment]
I have opened a potential PR, but my biggest concern is that I want to be able to override the `-Xlog:gc` option. I.e. the following are options that allow me to log gc to a pvc for later viewing:
```
-XX:+PrintFlagsFinal -Xlog:gc*:file=/logs/gc.log:time:filecount=5,filesize=25M  -XX:NativeMemoryTracking=summary -XX:+UnlockDiagnosticVMOptions -XX:+PrintNMTStatistics -XX:CompressedClassSpaceSize=150m -XX:MaxMetaspaceSize=150m -XX:MetaspaceSize=75m
```

The options for overriding it are to:

1. rely on the behavior specified here (https://bugs.openjdk.java.net/browse/JDK-8142952?focusedCommentId=13866870&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-13866870) and move `JAVA_OPTIONS` to be applied after `JAVA_DIAGNOSTICS`
2. keep `JAVA_DIAGNOSTICS` off and instead specify all options via `JAVA_OPTIONS` and hope that `JAVA_DIAGNOSTICS` doesn't drive other valuable logic.
3. Build logic into `JAVA_DIAGNOSTICS` so that it omits any duplicate options already specified in `JAVA_OPTIONS`
