### ISSUE TITLE
outdated images on docker hub

### ISSUE THREAD

**Issue by agebhar1** [fabric8io-images/s2i#246]
The latest tag(s) is/are (as of today) 7 months old and especially there is a newer version of Java 11 available:
```
[jboss@aab3f924e4d2 ~]$ java --version
openjdk 11.0.4 2019-07-16 LTS
OpenJDK Runtime Environment 18.9 (build 11.0.4+11-LTS)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.4+11-LTS, mixed mode, sharing)
```
build fresh image:
```
[jboss@8114089c81e5 ~]$ java -version
openjdk version "11.0.6" 2020-01-14 LTS
OpenJDK Runtime Environment 18.9 (build 11.0.6+10-LTS)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.6+10-LTS, mixed mode, sharing)
```
It would be great to update the repository by the PRs and trigger a new build to update the images on docker hub.

@rhuss let me know if you need some help

**Comment by rhuss** [comment]
I'm on it. I just released an update to run-java.sh and will make a new release of this images later today.

**Comment by agebhar1** [comment]
Great news @rhuss

**Comment by rhuss** [comment]
Just updated and pushed a 3.1.0 release of the s2i images (with updated deps and updated run-java.sh)

**Comment by agebhar1** [comment]
Thank you @rhuss. Tomorrow morning I'll try the new image.

**Comment by agebhar1** [comment]
Work's great, thanks again @rhuss.
