### ISSUE TITLE
mvn build should use --batch-mode flag

### ISSUE THREAD

**Issue by chirino** [fabric8io-images/s2i#75]
This would avoid:
<img width="1222" alt="openshift_web_console" src="https://cloud.githubusercontent.com/assets/103255/25411146/fef121ac-29e8-11e7-99ea-a6fec7598b9d.png">

**Comment by rhuss** [comment]
good find, makes much sense !

**Comment by vorburger** [comment]
@chirino @rhuss [seeing the -B here](https://github.com/fabric8io-images/s2i/blob/master/java/images/jboss/s2i/assemble#L122), I'm guessing that this meanwhile done - close this, or are you still seeing this?

**Comment by rhuss** [comment]
guess its fixed :)
