### ISSUE TITLE
Clean /tmp after build 

### ISSUE THREAD

**Issue by eljeko** [fabric8io-images/s2i#76]
It seems that
```
s2i/karaf/templates/s2i/assemble
```
doesn't clean the /tmp dir.

There is an option to delete the m2 (MAVEN_CLEAR_REPO=<somevalue>) but the /tmp dir contains also a ~/src with many files including the maven target dir with the <build>.zip.

This makes the image to be ~two times bigger.

**Comment by vorburger** [comment]
@eljeko would this not break incremental builds? Or am I getting this wrong and sources are always freshly injected anyway? Or, if we did this, would we have to also [save /tmp/src in s2i/save-artifacts](https://github.com/fabric8io-images/s2i/blob/master/java/templates/s2i/save-artifacts)?

If we do, then by default or as a new option? To be safe, perhaps best with a new option by env var, say `S2I_CLEAR_SRC` ?

BTW: Issue #12 is related to this - rather would not be needed, if we did this.
