### ISSUE TITLE
"Permission Denied" when running in OpenShift

### ISSUE THREAD

**Issue by EtienneK** [fabric8io-images/s2i#79]
Getting the following error when running the redhat-openjdk18-openshift s2i builder in OpenShift:

```
Starting the Java application using /opt/run-java/run-java.sh ...
 /opt/run-java/run-java.sh: line 44: cd: /home/jboss: Permission denied
```
Any ideas?

**Comment by dhirajsb** [comment]
Are you building your image on Windows? It can clobber file permissions.

**Comment by shuklaalok7** [comment]
The JAR gets built on OpenShift itself, after it clones the code from Git repo.

**Comment by verydarkmagic** [comment]
I'm having the same problem
`sh-4.2$ /opt/run-java/run-java.sh ${JAVA_ARGS}                                  
/opt/run-java/run-java.sh: line 44: cd: /home/jboss: Permission denied          
sh-4.2$ whoami                                                                  
whoami: cannot find name for user ID 1002000000                                 
sh-4.2$ ls                                                                      
ls: cannot open directory .: Permission denied                                  
sh-4.2$ pwd                                                                     
/home/jboss `

the weird part is that I can't even `ls`. Maybe it's not an issue with the script but the user that is created for this pod

**Comment by rafaeluchoa** [comment]
Add a environment variable $JAVA_APP_JAR with jar name.

https://issues.jboss.org/browse/OSFUSE-580

**Comment by rhuss** [comment]
Tbh, i don't think this is an issue anymore, because we are setting now the permissions as recommended by openshift:

https://github.com/fabric8io-images/s2i/blob/b5b29eab984e8583a80a55f922787a06719a3d32/java/images/rhel/Dockerfile#L86-L87

I'm closing this issue for now, please feel free to reopen it if there is still a problem.

**Comment by CodeKlaudia** [comment]
I believe that I might be having the same permissions issue with /deployments/run-java.sh

https://stackoverflow.com/questions/77208732/managed-kafka-instance-openshift-developer-sandbox-denied-permission-deploy
