### ISSUE TITLE
Error while pushing image to docker registry

### ISSUE THREAD

**Issue by vsedykh** [fabric8io-images/s2i#80]
Hi there!

I have openshift origin installed in clodes environmet, so images cannot be pulled from public repositories. I need to push images manualy. My steps:
1. pull fabric8/s2i-java:2.0 on computer with internet
2. save this image to file
3. copy saved image to server where openshift is installed
4. on master node load image
5. get token with: oc whoami -t
6. login to docker: docker login -p <TOKEN> 172.30.1.1:5000
7. tag image: docker tag fabric8/s2i-java:2.0 172.30.1.1:5000/fabric8/s2i-java:2.0
8. push image: docker push 172.30.1.1:5000/fabric8/s2i-java:2.0
last command failed with exception:
The push refers to a repository [172.30.1.1:5000/fabric8/s2i-java]
5f70bf18a086: Preparing
d32ed8bcc29a: Preparing
7a3918f43401: Preparing
8794367458d9: Preparing
7b2b8ba72018: Preparing
ef12ec351380: Waiting
aa97a88ab73b: Waiting
976e0cc32ff4: Waiting
d709326f53ea: Waiting
cea2ed19e339: Waiting
33e60bc17c03: Waiting
8515814a316b: Waiting
7fa540ae36b6: Waiting
509be91f37b7: Waiting
23308a2d4711: Waiting
9d53f6387fe5: Waiting
0219e8c42d4a: Waiting
ed3fbbd74f2c: Waiting
fef12de4c7da: Waiting
3bf2c105669b: Waiting
85c6e373d858: Waiting
dc1e2dcdc7b6: Waiting
unauthorized: authentication required

Any ideas how it can be fixed?

**Comment by rhuss** [comment]
If you push the openshift internal registry, you need to provide the authentication when calling `docker push`, e.g. a 
```
docker login -u `oc whoami` -p `oc whoami -t` <your registry>
```

As this is not related to the s2i image, I'm so free and close this issue.
